# permissions for end users to edit namespacecleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacecleaner-editor-role
rules:
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - namespacecleaners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - namespacecleaners/status
  verbs:
  - get
