# permissions for end users to view namespacecleaners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacecleaner-viewer-role
rules:
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - namespacecleaners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - namespacecleaners/status
  verbs:
  - get
