# permissions for end users to view secretsynclers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsyncler-viewer-role
rules:
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - secretsynclers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - secretsynclers/status
  verbs:
  - get
