# permissions for end users to edit secretsynclers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretsyncler-editor-role
rules:
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - secretsynclers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synclers.synclair.syndikate.io
  resources:
  - secretsynclers/status
  verbs:
  - get
